name: Static-Prisons
version: '${project.version}'
description: This plugin allows static prisons to run!
main: me.staticstudios.prisons.Main
api-version: 1.17
depend: [ WorldEdit, WorldGuard, LuckPerms ]
commands:
  test:
    description: a
    permission: static.staff.developer
  test2:
    description: a
    permission: static.staff.developer
  setplayerrank:
    description: a
    permission: static.staff.admin
  addchattag:
    description: a
    permission: static.staff.admin
  addallchattags:
    description: a
    permission: static.staff.sradmin
  removechattag:
    description: a
    permission: static.staff.admin
  setstaffrank:
    description: a
    permission: static.staff.sradmin
  modifystats:
    description: a
    aliases:
      - modstats
    permission: static.staff.admin
  getnewpickaxe:
    description: a
  sell:
    description: a
  rankup:
    description: a
  rankupmax:
    description: a
  gui:
    description: a
    aliases:
      - help
  chattags:
    aliases:
      - tags
    description: a
  prestige:
    description: a
  enderchest:
    description: a
    aliases:
      - echest
  enderchestsee:
    description: a
    permission: static.staff.admin
    aliases:
      - echestsee
  renameitem:
    description: a
    permission: static.staff.mod
    aliases:
      - nameitem
  auctionhouse:
    description: a
    aliases:
      - ah
      - auction
  settings:
    description: a
    aliases:
      - autosell
      - chatfilter
      - tips
  privatemine:
    aliases:
      - pmine
      - pmines
  mobilesupport:
    description: a
  color:
    description: a
    aliases:
      - bold
      - italic
      - underline
  stats:
    description: a
  schedulerestart:
    description: a
    permission: static.staff.admin
  schedulestop:
    description: a
    permission: static.staff.admin
  broadcast:
    description: a
    permission: static.staff.mod
  discord:
    description: a
  coinflip:
    description: a
    aliases:
      - cf
  tokenflip:
    description: a
    aliases:
      - tf
  npcdiag:
    description: a
  spawn:
    description: a
    aliases:
      - s
  mines:
    description: a
  warps:
    description: a
    aliases:
      - warp
  store:
    description: a
  fly:
    description: a
  crates:
    description: a
  leaderboards:
    description: a
    aliases:
      - lb
  _:
    description: vote/store
    permission: op
  votes:
    description: a
  nickname:
    description: a
    aliases:
      - nick
  customitems:
    description: a
    permission: static.staff.admin
  keyall:
    description: a
    permission: static.staff.admin