name: Static-Prisons
version: '1.0-SNAPSHOT'
description: This plugin allows static prisons to run!
main: net.staticstudios.prisons.StaticPrisons
api-version: 1.18
depend: [ WorldEdit, WorldGuard, LuckPerms, WorldBorderAPI, ProtocolLib ]
commands:
  test:
    description: a
    permission: static.staff.developer
  test2:
    description: a
    permission: static.staff.developer
  static-mines:
    permission: static.staff.admin
    description: Command to be used by the StaticMines dependency
  setplayerrank:
    description: a
    permission: static.staff.admin
  addchattag:
    description: a
    permission: static.staff.admin
  addallchattags:
    description: a
    permission: static.staff.sradmin
  removechattag:
    description: a
    permission: static.staff.admin
  setstaffrank:
    description: a
    permission: static.staff.sradmin
  modifystats:
    description: a
    aliases:
      - modstats
    permission: static.staff.admin
  getnewpickaxe:
    description: a
    aliases:
      - pick
  sell:
    description: a
    aliases:
      - sellall
  rankup:
    description: a
  rankupmax:
    description: a
  gui:
    description: a
    aliases:
      - help
      - menu
  chattags:
    aliases:
      - tags
    description: a
  prestige:
    description: a
  enderchest:
    description: a
    aliases:
      - echest
  enderchestsee:
    description: a
    permission: static.staff.admin
    aliases:
      - echestsee
  renameitem:
    description: a
    permission: static.staff.moderator
    aliases:
      - nameitem
  auctionhouse:
    description: a
    aliases:
      - ah
      - auction
  settings:
    description: a
    aliases:
      - autosell
      - chatfilter
      - tips
      - theme
  privatemine:
    aliases:
      - pmine
      - pmines
  mobilesupport:
    description: a
  color:
    description: a
    aliases:
      - bold
      - italic
      - underline
  stats:
    description: a
  schedulerestart:
    description: a
    permission: static.staff.admin
  schedulestop:
    description: a
    permission: static.staff.admin
  broadcast:
    description: a
    permission: static.staff.moderator
  discord:
    description: a
  coinflip:
    description: a
    aliases:
      - cf
  tokenflip:
    description: a
    aliases:
      - tf
  npcdiag:
    description: a
  spawn:
    description: a
    aliases:
      - s
  mines:
    description: a
    aliases:
      - mine
  warps:
    description: a
    aliases:
      - warp
  store:
    description: a
    aliases:
      - buy
  fly:
    description: a
  crates:
    description: a
  leaderboards:
    description: a
    aliases:
      - lb
  _:
    description: vote/store
    permission: op
  votes:
    description: a
  nickname:
    description: a
    aliases:
      - nick
  customitems:
    description: a
    permission: static.staff.admin
  keyall:
    description: a
    permission: static.staff.admin
  updateleaderboards:
    description: a
    permission: static.staff.admin
  refill:
    description: a
    permission: static.staff.moderator
  withdraw:
    description: a
    aliases:
      - balnote
      - tokennote
      - moneynote
  pay:
    description: a
    aliases:
      - transfer
  dropitem:
    description: a
  reclaim:
    description: a
  listplayerrank:
    description: a
    permission: static.staff.moderator
  liststaffrank:
    description: a
    permission: static.staff.moderator
  addpickaxexp:
    description: a
    permission: static.staff.admin
  addpickaxeblocksmined:
    description: a
    permission: static.staff.admin
  enchant:
    description: a
    aliases:
      - enchants
      - customenchants
  dailyrewards:
    description: a
  island:
    description: a
    aliases:
      - is
      - c
      - cell
  exemptfromleaderboards:
    desription: a
    aliases:
      - dontdisplayonlb
    permission: static.staff.admin
  balance:
    description: a
    aliases:
      - bal
  tokens:
    description: a
    aliases:
      - tokenbal
  shards:
    description: a
    aliases:
      - shardbal
  givevote:
    desription: a
    permission: static.staff.admin
  backpack:
    desription: a
    aliases:
      - bp
  message:
    description: a
    aliases:
      - msg
      - tell
      - w
      - whisper
  reply:
    description: a
    aliases:
      - r
  watchmessages:
    description: a
    permission: static.staff.admin
    aliases:
      - msgspy
      - socialspy
  trash:
    description: a
    aliases:
      - bin
      - trashcan
  multiplier:
    description: a
    aliases:
      - multi
  debug:
    description: a
    permission: static.staff.admin
  rules:
    description: a
  reload-config:
    description: a
    permission: op
  level:
    description: a
    aliases:
      - lvl
      - levelup
      - xp