name: Static-Prisons
version: '1.0-SNAPSHOT'
description: This plugin allows static prisons to run!
main: me.staticstudios.prisons.Main
api-version: 1.17
depend: [ WorldEdit, WorldGuard, LuckPerms ]
commands:
  test:
    description: a
    permission: static.staff.developer
  test2:
    description: a
    permission: static.staff.developer
  setplayerrank:
    description: a
    permission: static.staff.admin
  addchattag:
    description: a
    permission: static.staff.admin
  addallchattags:
    description: a
    permission: static.staff.sradmin
  removechattag:
    description: a
    permission: static.staff.admin
  setstaffrank:
    description: a
    permission: static.staff.sradmin
  modifystats:
    description: a
    aliases:
      - modstats
    permission: static.staff.admin
  getnewpickaxe:
    description: a
  sell:
    description: a
  rankup:
    description: a
  rankupmax:
    description: a
  gui:
    description: a
    aliases:
      - help
  chattags:
    aliases:
      - tags
    description: a
  prestige:
    description: a
  enderchest:
    description: a
    aliases:
      - echest
  enderchestsee:
    description: a
    permission: static.staff.admin
    aliases:
      - echestsee
  renameitem:
    description: a
    permission: static.staff.mod
    aliases:
      - nameitem
  auctionhouse:
    description: a
    aliases:
      - ah
      - auction
  settings:
    description: a
    aliases:
      - autosell
      - chatfilter
      - tips
  privatemine:
    aliases:
      - pmine
      - pmines
  mobilesupport:
    description: a
  color:
    description: a
    aliases:
      - bold
      - italic
      - underline